version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "80:80"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${AZURE_DB_HOST}:3306/${AZURE_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${AZURE_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${AZURE_DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      